---
- name: httpd and mariadb are running
  hosts: 192.168.56.114
  remote_user: worker
  become: yes
  tasks:
    - service:
        name: "{{ item }}"
        state: started
      loop:
        - httpd
        - mariadb

