---
# tasks file for web_server
- name: Ensure Apache is installed
  package:
    name: httpd
    state: latest
- name: Ensure Apache Service is restarted
  service:
    name: httpd
    state: restarted