---
- name: create a user
  hosts: localhost
  become: true
  vars_files:
    secret.yml
  tasks:
    - name: create a user
      user:
        name: "{{ username }}"
        password: "{{ pwhash }}"

