---
- name: touch file
  hosts: 192.168.56.114
  remote_user: worker
  tasks:
    - file:
        mode: 0644
        path: /home/worker/fileA
        owner: worker
        group: worker
        state: touch

