---
- name: Render Jinja loop test
  hosts: 192.168.56.114
  remote_user: worker
  gather_facts: no
  tasks:
    - name: Render jinja template
      template:
        src: jinja-loop.j2
        dest: ~/test/rendered_template_loop.txt
      vars:
         my_list:
           - APPLE
           - SAMSUNG
           - LG
