---
- name: Render Jinja if test
  hosts: 192.168.56.114
  remote_user: worker
  gather_facts: no
  tasks:
    - name: Render jinja template
      template:
        src: jinja-if.j2
        dest: test/rendered_template_if.txt
      vars:
        my_variable: "Candy"
